### ISSUE TITLE
cdn 支持

### ISSUE THREAD

**Issue by anvyzhang** [chloerei/campo#10]
assets
发布脚本
图像处理
文件上传
这些考虑支持cdn吗

**Comment by chloerei** [comment]
现在想法是如果需要这些功能可以 fork 出去维护自己的版本。

**Comment by chloerei** [comment]
例如对上传文件的支持，可以加一个 carrierwave 的配置 config/initializers/carrierwave.rb

``` ruby
CarrierWave.configure do |config|
  config.asset_host = "http://i.codecampo.com" # 你的 CDN 域名
end
```

这样上传后的图片的 URL 就会变成 `http://i.codecampo.com/uploads/attachments/...`，再用七牛这类可以从源网站抓文件的 CDN 就可以切过去了。

要上传到其他云存储就看 https://github.com/carrierwaveuploader/carrierwave 的具体配置。

assets 也是配置 Rails 的 `config.asset_host` 。
