### ISSUE TITLE
server configs

### ISSUE THREAD

**Issue by vjaykoogu** [chloerei/campo#11]
Nice work man.... i really like your work, can you tell me wats the configuration of the current system running i mean to say server configs...

its working quite fast actually... loving it

**Comment by chloerei** [comment]
Thanks! The server running codecampo.com ? It's https://www.digitalocean.com/ (or [referral lInk](https://www.digitalocean.com/?refcode=d8d2d46dd664)) $10/mo plan, San Francisco 1 region, Ubuntu 12.04 LTS.

**Comment by vjaykoogu** [comment]
why you are not using proper version...  why fetching from github ? ex: github: "rails/rails". It's not fetching gem. can we stik to proper gem please...

**Comment by chloerei** [comment]
When I create the project, I want to use newset rails feature, like enum. I thought rails 4.1.0 will be release before campo 3 release...but I wrong.

Rails's github repo is very large, bundle install will be slow, so I will update Gemfile to use 4.1.0.rc1 in rubygems soon.

**Comment by vjaykoogu** [comment]
ok thats great.. thought of adding any new features ?

whats is your twitter handle man ?

**Comment by chloerei** [comment]
Now it's 4.1.0.rc1

I want to keep code size small, current no big feature in plan, just let exists function work better. But I want to design a better UI.

My twitter ID is [@chloerei](https://twitter.com/chloerei)

**Comment by vjaykoogu** [comment]
thanks....how about displaying user profile pic who like the post. like foursquare.. foursquare displays profile pic who like the post or checkin...

**Comment by vjaykoogu** [comment]
Forgot the mention to add Follow and Unfollow options for users...  that will be great

**Comment by chloerei** [comment]
What does "forgot the mention" mean?

**Comment by vjaykoogu** [comment]
sorry...   Add Follow and Unfollow options for users... that will be great

**Comment by chloerei** [comment]
I had considered, but I'm afraid to re-invent twitter(does it need a timeline?), so not completed yet.

**Comment by vjaykoogu** [comment]
yep it will be cool really... Users can follow each other and timeline too, similar to twitter but not twitter. i dont think we have similar app like this.

Why don't you use devise and omniauth for authentication, coz as far as i know (http://github.com/diaspora/diaspora) did the same thing later they shifted to devise and omniauth for better performance.

**Comment by chloerei** [comment]
Devise is hard for me, I tried several times to read the source code, still do not understand the structure. When customize authentication process,  I must overwrite some hooks function that I don't know what's meaning, that let me feel uncontrollable. Write own authentication is easy to customize, all code is in the same project.

omniauth is good, who want 3rd part authentication should use it. Depends on different situations, 3rd part authentication is not a must have feature. and 3rd part authentication cause some experience issues, Campo need unique username and email, if it's not completed by 3rd part authentication, user still need to fill a registration form. so I'm not implement yet.

**Comment by vjaykoogu** [comment]
So that means  we can see follow and timeline features on campo ...

**Comment by chloerei** [comment]
Uncertain ... current not woking on it. I envisioned Campo is a poor function and easy to customize project.

**Comment by vjaykoogu** [comment]
ohh ok

**Comment by vjaykoogu** [comment]
Sorry for dumb question but can we install vagrant on Ubuntu which is running on vmware?

im using windows 7, using Vmware to run my Ubuntu.

**Comment by chloerei** [comment]
Vagrant VMware providers need buying license, so I have no test it. http://www.vagrantup.com/vmware

Vagrant is use for building a independent development environment（clean and repeatable）, looks like you want to install to an exists vm? Maybe you don't need vagrant. Check [bin/setup](https://github.com/chloerei/campo/blob/master/bin/setup.sh), that's what Campo need for prepare:
- install denpendency via apt
- install Elasticsearch from it's site
- create PostgreSQL user
- install rvm
- install ruby via rvm
- cp config yml

Vagrant is no need for deployment.

**Comment by vjaykoogu** [comment]
and what about docker ? coz i googled but din't get any proper guide running on VMWARE. :(

**Comment by chloerei** [comment]
Without vagrant:
1. Login to Ubuntu
2. `git clone` this repo
3. cd repo directory
4. run `./bin/setup`
5. run `rails s` start server(development mode)

Are you familiar with Rails application? Indeed deploying a Rails app is no easy.

**Comment by chloerei** [comment]
I'm not familiar with docker, will have a try in the feature.

**Comment by vjaykoogu** [comment]
how about google+ chat i think i can learn alot from u... can become master in rails like u.

**Comment by chloerei** [comment]
I don't like chat, sorry. :metal:

**Comment by vjaykoogu** [comment]
ok no isssue... :+1:
