### ISSUE TITLE
addon features

### ISSUE THREAD

**Issue by vjaykoogu** [chloerei/campo#21]
a) i think campo should have follow/un-follow user feature to track favorite user activity.
b)  E-mail confirmation feature to track fake users. also can be used for sending mails when some1 comments or likes post. 
*\* Noification or settings page ( user can control what he want in his mails )
 -> I don't want new posts by email. 
-> I want one email every day. 
-> Someone starts following me.

**Comment by chloerei** [comment]
Great, I'm plan to implement this feature.

But I'm busy with another project, are you interested to implement it?

**Comment by vjaykoogu** [comment]
yep.. bit busy with another project... but love to see those features on campo.

**Comment by chloerei** [comment]
Now add a email confirmation feature, you can test in http://codecampo.com .

Current no have any limit for unconfirmed user, plan to set limit for receive email notification and allow setting notification.

Activity feature will come more later.

**Comment by vjaykoogu** [comment]
great but the message should place down... or above navbar in separate div...

**Comment by vjaykoogu** [comment]
mails are directed to spam but working great.

**Comment by chloerei** [comment]
Now support comment/mention email notification, and have a notification settings page.

**Comment by vjaykoogu** [comment]
how about fb and google signup, coz most users nowadays prefer one identity over internet... why have to create multiple identity. hope you get my point.

**Comment by chloerei** [comment]
No plan to support 3rd party authentication, reasons:
- No one provider cover all user, if support one, then must support multiple. It's annoying.
- For current function, unique Email and username is required, if 3rd pary account info not satisfied, user still need to filling a form, I think it's not friendly. 
- The best provider Google is not accessable in my country (China style, same as Facebook), so I have no incentive to do it.

In fact I love google sign in, it's more safe.

**Comment by vjaykoogu** [comment]
how about inviting friends from fb, Google or by email. to campo. User invitation.

**Comment by vjaykoogu** [comment]
why to fill username while signup best solution is to crop from email or from fullname.can keep it short ( Fullname, email-id, password )
![short signup](https://cloud.githubusercontent.com/assets/87112/2688547/e90c431a-c2aa-11e3-876e-5123ac74b318.png)

**Comment by vjaykoogu** [comment]
why to open new pop-up box on click on " Resend Email " button. best option is to replace the text with " Verification email sent! Click again to resend "

**Comment by chloerei** [comment]
Imitate Twitter, but it's no important.

**Comment by chloerei** [comment]
I mean the pop-up box style is not important.

And, in Twitter and Github, no authenticated user still can use most function, except email notification. It depends on business, let user easy to try something or not. there is a `confirm_email_required` filter method, it's better to fork and customized.

**Comment by vjaykoogu** [comment]
i have added gem 'nprogress-rails' and it works great.

**Comment by chloerei** [comment]
Could you add a nprogress-rails pull request? (What's your site address?)

**Comment by vjaykoogu** [comment]
no its on my local lapi.

**Comment by vjaykoogu** [comment]
just add gem 'nprogress-rails' into gem file and 

-- application.js.coffee 
#= require nprogress
#= require nprogress-turbolinks

-- application.css.scss
*= require nprogress
*= require nprogress-bootstrap

thats it done. :+1:  i tried it on my local system it workd fine.

**Comment by chloerei** [comment]
Done. I download the last version from https://github.com/rstacruz/nprogress, I think vendor better than unofficial gem.

**Comment by vjaykoogu** [comment]
yep saw it. looking great... :+1:

**Comment by vjaykoogu** [comment]
how about displaying users pic when they like post. addon from my friend.

ex:  
![pics](https://cloud.githubusercontent.com/assets/87112/2708616/036178e8-c4ae-11e3-8a07-ee2071969ab9.png)

**Comment by chloerei** [comment]
Look nice. What application is the screenshot from?

**Comment by vjaykoogu** [comment]
https://www.bloglovin.com i love their design.

**Comment by vjaykoogu** [comment]
how to login as admin in campo ?

**Comment by chloerei** [comment]
Edit config/config.yml , add admin email to `admin_emails` column, example:

``` ruby
production:
  admin_emails:
    - admin@example.com
```

Replace email with your real email, restart server, then user who has this email will become admin, then visit `/admin` to admin page.

**Comment by vjaykoogu** [comment]
hope you like the design  https://github.com/chloerei/campo/issues/21#issuecomment-40491488

**Comment by chloerei** [comment]
had you remove `~` from user profile's route? That will conflict with other routes.

**Comment by vjaykoogu** [comment]
yep i have removed it. kept it simple.

**Comment by chloerei** [comment]
So you must add extra code to select routes and limit username not conflict with site function.

**Comment by chloerei** [comment]
Move username route scope to bottom, that will fixed route issues.

**Comment by vjaykoogu** [comment]
i wonder how much load campo can take.. i mean to say amount of traffic... ex: 1m users per month. im serious about it.. :100:

**Comment by vjaykoogu** [comment]
please add invoker gem to managing processes in development environment.
http://invoker.codemancers.com/

**Comment by chloerei** [comment]
Don't feel it's necessary.

**Comment by vjaykoogu** [comment]
what do think about this  https://github.com/chloerei/campo/issues/21#issuecomment-40627918

**Comment by chloerei** [comment]
I like the design, but I'm busying in another project, so will not add new feature to campo recently.

**Comment by vjaykoogu** [comment]
plz add https://github.com/jhnvz/retina_rails gem. uploaded image looks so beautiful with this gem.
