### ISSUE TITLE
注册后不发送邮件的问题

### ISSUE THREAD

**Issue by windy** [chloerei/campo#25]
在注册用户后有时不发送邮件

我仔细看了 `campo` 代码, 没有看到 User.save 时调用 `UserMailer.confirmation(current_user.id).deliver` 是不是我看漏了, 弄错了? 

如果不是的话, @Rei 帮我确认一下, 我 fix 一下.

**Comment by chloerei** [comment]
是没调用，campo 本身的问题。我在 campo 上修复吧。

**Comment by windy** [comment]
不过之前我注册的时候印象中是发了, 现在本地加了日志调试的时候确认没调用. 可能以前印象错了~

**Comment by chloerei** [comment]
https://github.com/chloerei/campo/commit/aa626187c3597c8e3103a8c22fe026f74dfd406d

修复了。可以 merge 或者 copy 到你的项目。

**Comment by windy** [comment]
@chloerei OK, 已经合入~ 辛苦:)
