### ISSUE TITLE
这个项目真的可以使用Vagrant么

### ISSUE THREAD

**Issue by feng92f** [chloerei/campo#33]
看这个文件不像可以的样子啊 https://github.com/chloerei/campo/blob/master/Vagrantfile
我没学过Ruby 不要骗我
Master的代码真的可以部署么 我咋跑不起来

**Comment by chloerei** [comment]
没学过 Ruby 不要用了，这个项目部署不是零门槛的。

**Comment by feng92f** [comment]
好捉急

**Comment by feng92f** [comment]
@chloerei  setup里是不是缺 apt-get install ruby-bundler ，还有12.04默认是ruby 1.8我升级到2.1算是可以了。。。

**Comment by chloerei** [comment]
https://github.com/chloerei/campo/wiki/Getting-Started

Setup

```
/vagrant $ ./script/setup.sh
```

This script will install all dependency.

我已经多次测试安装脚本了，如果你遇到问题就把问题细节列出来，捉急也没用。

**Comment by feng92f** [comment]
@chloerei 好的 我稍后给你反馈下细节哈。 又遇到一个问题 就是resque中的任务一直都是pending。 没有workder 去处理任务， 我的邮件发不出来。

**Comment by chloerei** [comment]
开发环境，resque woker 要手工启动 `QUEUE=* rake resque:work`。

**Comment by feng92f** [comment]
:beers::beers::beers::beers::beers::beers::beers::beers: 哈worker启动了

**Comment by marvin-min** [comment]
这个我们真需要在这里讨论吗？
Marvin Min, Software Engineer

Active Network

Corporate
QinFengGe B201 68 Keji No. 2 Rd.
Xian, China 710075
Mobile 18910813420
Marvin.Min@ActiveNetwork.commailto:Lucien.Wang@ActiveNetwork.com
www.ActiveNetwork.comhttp://www.activenetwork.com/

We power the world's activities and connect people with the things they love, want and need to do.

**Comment by chloerei** [comment]
移步 http://codecampo.com/ 讨论。
