### ISSUE TITLE
problems with reset password

### ISSUE THREAD

**Issue by marvin-min** [chloerei/campo#38]
Hi, @chloerei . I forgot my password for http://codecampo.com/login. However I can't login after reset my password. Could you help? thanks.my email: minxiaorong[at]126.com

**Comment by chloerei** [comment]
Can you complete reset process？

**Comment by marvin-min** [comment]
@chloerei  I had finished the reset process. However I sitll can't login correctly.

Thanks

**Comment by marvin-min** [comment]
Resolved. @chloerei Thanks.
